name: clipboard_manager
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  clipboard_watcher: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_list_view: ^1.1.21
  provider: ^6.0.3
  super_clipboard: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

