name: clipboard_manager
description: A new Flutter project.
publish_to: 'none'

version: 0.4.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  clipboard_watcher: ^0.2.0
  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.1
  flutter_list_view: ^1.1.21
  flutter_rust_bridge: 1.77.1
  flutter_useful_widgets:
    git: 
      url: https://github.com/guchengxi1994/flutter_useful_widgets
  flutter_smart_dialog: ^4.9.0+6
  i18n_extension: ^9.0.0
  image: ^4.0.17
  provider: ^6.0.3
  super_clipboard: ^0.4.0
  uuid: ^3.0.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  ffigen: ^8.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0


dependency_overrides:  
  cli_util: ^0.4.0
  flutter_useful_widgets:
    path: D:\github_repo\flutter_useful_widgets

flutter_icons:
  windows:
    generate: true
    image_path: "assets/clipboard.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/clipboard.png"
  linux:
    generate: true
    image_path: "assets/clipboard.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/fonts/

  fonts:
    - family: 思源
      fonts:
        - asset: assets/fonts/SourceHanSans-Medium.ttc
